version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./.sql:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080